export const IPC = {
  FILE_SAVE:       'file:save',
  FILE_OPEN:       'file:open',
  FILE_NEW:        'file:new',
  FILE_READ:       'file:read',
  FILE_WATCH:      'file:watch',
  FILE_UNWATCH:    'file:unwatch',
  FILE_CHANGED:    'file:changed',
  EXPORT_PDF:      'export:pdf',
  EXPORT_MD:       'export:md',
  APP_GET_VERSION: 'app:getVersion',
  APP_SET_DIRTY:    'app:setDirty',
  APP_SAVE_REQUEST: 'app:saveRequest',
  APP_SAVE_REPLY:   'app:saveReply',
  DIALOG_CONFIRM_UNSAVED: 'dialog:confirmUnsaved',
  REFERENCE_OPEN_DOC: 'reference:openDoc',
  REFERENCE_READ:     'reference:read',
  NOTEBOOK_LIST:           'notebook:list',
  NOTEBOOK_CREATE_SUBJECT: 'notebook:createSubject',
  NOTEBOOK_CREATE:         'notebook:create',
  NOTEBOOK_SET_COLLECTION: 'notebook:setCollection',
  NOTEBOOK_DELETE:         'notebook:delete',
  NOTEBOOK_RENAME:         'notebook:rename',
  SEARCH_GLOBAL:           'search:global',
  ALEXANDRIA_OPEN_TAB:     'alexandria:openTab',
  VAULT_GET:               'vault:get',
  VAULT_SELECT:            'vault:select',
} as const
